#!/bin/sh

# Exit if any subcommand fails
set -e

CLEAR_LINE='\r\033[K'
GREEN='\033[0;32m'

./setup_steps/dependencies
./setup_steps/dotfiles
./setup_steps/vim
./setup_steps/zsh

source ~/.zshrc

printf "${CLEAR_LINE}🎉${GREEN}   Finished!${NO_COLOR}\n"
