#!/bin/bash

# update homebrew
brew update

# GNU tools
#
# Install GNU core utilities (those that come with OS X are outdated)
install coreutils

# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
install findutils

# Install Bash 4
install bash

# Install more recent versions of some OS X tools
tap homebrew/dupes
install homebrew/dupes/grep

# Update ~/.bash_profile to overrite the Mac versions for these tools
echo -e "# Use GNU tools over Mac one's" >> ~/.bash_profile
echo -e 'export PATH=$(--prefix coreutils)/libexec/gnubin:$PATH\n' >> ~/.bash_profile

# Binaries
#
install git
install imagemagick
install jq
install erlang
install node
install gnuplot
install pstree
install tree
install rename
install cmake
install ack
install node
install gnu-sed --default-names
install ctags
install git-flow
install ssh-copy-id
install vim
cleanup

# Apps
#
# Automate the installation of Mac apps and fonts through HomeCask
install caskroom/cask/brew-cask

cask install iterm2
cask install alfred
cask install dropbox
cask install google-chrome
cask install firefox
cask install vagrant
cask install virtualbox
cask install mou
cask install spotify
cask install skype
cask install transmission
cask install vlc
cask install sequel-pro
cask install cloudapp
cask install dash
cask install evernote

cask alfred link
cask cleanup
