#!/bin/bash

# ask for the administrator password upfront
sudo -v

# menu bar: hide the Time Machine, Volume and User icons
defaults write ~/Library/Preferences/ByHost/com.apple.systemuiserver.* dontAutoLoad -array \
  '/System/Library/CoreServices/Menu Extras/TimeMachine.menu' \
  '/System/Library/CoreServices/Menu Extras/Volume.menu' \
  '/System/Library/CoreServices/Menu Extras/User.menu' \

# automatically quit printer app once the print jobs complete
defaults write com.apple.print.PrintingPrefs 'Quit When Finished' -bool true

# disable the "Are you sure you want to open this application?" dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# disable the crash reporter
defaults write com.apple.CrashReporter DialogType -string 'none'

# set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 2
defaults write NSGlobalDomain InitialKeyRepeat -int 15

#  Finder
#-----------------------------------------------
# show hidden files by default
defaults write com.apple.finder AppleShowAllFiles -bool true

# show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# show path bar
defaults write com.apple.finder ShowPathbar -bool true

# allow text selection in Quick Look
defaults write com.apple.finder QLEnableTextSelection -bool true

# search the current folder by default
defaults write com.apple.finder FXDefaultSearchScope -string 'SCcf'

# disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# avoid creating .DS_Store files on network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# show the ~/Library folder
chflags nohidden ~/Library

# Kill Finder to load the new configuration
killall Finder > /dev/null 2>&1

