#!/bin/bash

# Homebrew
if test ! $(which brew); then
  echo "Installing homebrew..."
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo -e "\n# Homebrew Cask settings" >> ~/.bash_profile
echo -e 'export HOMEBREW_CASK_OPTS="--appdir=/Applications"\n' >> ~/.bash_profile

sh ./brew_bundle

# Mac OS X Configuration
sh ./osx
