#!/bin/sh

# Exit if any subcommand fails
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

printf "${CLEAR_LINE}Installing curl and other essentials"

sudo apt-get -y -q -q install curl build-essential tree htop xsel > /dev/null

printf "${CLEAR_LINE}Installing Powerline fonts"

sudo apt-get -q -q install fonts-powerline

printf "${CLEAR_LINE}Installing neovim"

sudo apt-get -y -q -q install neovim > /dev/null

printf "${CLEAR_LINE}Installing tmux"

sudo apt-get -y -q install tmux > /dev/null

printf "${CLEAR_LINE}Installing Fira Code font\n\n"

sudo apt-get -y -q install fonts-firacode

printf "\n\n${CLEAR_LINE}Installing rcm\n\n"

wget -qO - https://apt.thoughtbot.com/thoughtbot.gpg.key | sudo apt-key add -
echo "deb http://apt.thoughtbot.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list
sudo apt-get -q update
sudo apt-get -q install rcm
