#!/bin/sh

# Exit if any subcommand fails
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

printf "${CLEAR_LINE}Installing curl"

sudo apt-get -y install curl > /dev/null

printf "${CLEAR_LINE}Installing neovim"

sudo apt-get -y install neovim > /dev/null

printf "${CLEAR_LINE}Installing tmux"

sudo apt-get -y install tmux > /dev/null

printf "${CLEAR_LINE}Installing rcm"

wget -qO - https://apt.thoughtbot.com/thoughtbot.gpg.key | sudo apt-key add -
echo "deb http://apt.thoughtbot.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/thoughtbot.list
sudo apt-get update
sudo apt-get install rcm

printf "${CLEAR_LINE}Installing The Fuck"

sudo apt-get -y install python-pip python-dev > /dev/null
sudo pip install psutil thefuck > /dev/null
