#!/bin/sh

# Exit if any subcommand fails
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NO_COLOR='\033[0m'
CLEAR_LINE='\r\033[K'

printf "${CLEAR_LINE}Installing zsh"
sudo apt-get -y install zsh > /dev/null

printf "${CLEAR_LINE}Intalling Oh My Zsh"

sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

if [ -d "~/.oh-my-zsh" ]; then
  printf "${CLEAR_LINE}Oh My Zsh plugins already installed"
else
  printf "${CLEAR_LINE}Installing Oh My Zsh syntax highlighting plugin"
  git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
fi

rcup
